/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.iesfm.ejerciciobotones;

/**
 *
 * @author MiguelSánchezMuñoz
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        jBAzul.setVisible(false);
        jBVerde.setVisible(false);
        jBReset.setVisible(false);
        jBRojo.setVisible(false);
        jLabelMensaje.setText("Pulsa el boton inicio para empezar");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBVerde = new javax.swing.JButton();
        jBRojo = new javax.swing.JButton();
        jBAzul = new javax.swing.JButton();
        jBInicio = new javax.swing.JButton();
        jBReset = new javax.swing.JButton();
        jLabelMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mi primera ventana");

        jBVerde.setText("Verde");
        jBVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVerdeActionPerformed(evt);
            }
        });

        jBRojo.setText("Rojo");
        jBRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRojoActionPerformed(evt);
            }
        });

        jBAzul.setText("Azul");
        jBAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAzulActionPerformed(evt);
            }
        });

        jBInicio.setText("Inicio");
        jBInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInicioActionPerformed(evt);
            }
        });

        jBReset.setText("Reset");
        jBReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jBInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBReset)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBVerde)
                        .addGap(50, 50, 50)
                        .addComponent(jBRojo)
                        .addGap(53, 53, 53)
                        .addComponent(jBAzul)))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBInicio)
                    .addComponent(jBReset))
                .addGap(49, 49, 49)
                .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBVerde)
                    .addComponent(jBRojo)
                    .addComponent(jBAzul))
                .addGap(70, 70, 70))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVerdeActionPerformed
        // TODO add your handling code here:
        jBAzul.setVisible(false);
        jBRojo.setVisible(false);
        jBInicio.setVisible(false);
        jLabelMensaje.setText("Has pulsado el boton verde");
    }//GEN-LAST:event_jBVerdeActionPerformed

    private void jBInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInicioActionPerformed
        // TODO add your handling code here:
        jBAzul.setVisible(true);
        jBVerde.setVisible(true);
        jBReset.setVisible(true);
        jBRojo.setVisible(true);
        jLabelMensaje.setText("Pulsa un boton de los que indican un color");

    }//GEN-LAST:event_jBInicioActionPerformed

    private void jBResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBResetActionPerformed
        // TODO add your handling code here:
        jBAzul.setVisible(true);
        jBVerde.setVisible(true);
        jBInicio.setVisible(true);
        jBRojo.setVisible(true);
        jLabelMensaje.setText("Has pulsado el boton reset");

    }//GEN-LAST:event_jBResetActionPerformed

    private void jBRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRojoActionPerformed
        // TODO add your handling code here:
        jBAzul.setVisible(false);
        jBVerde.setVisible(false);
        jBInicio.setVisible(false);
        jLabelMensaje.setText("Has pulsado el boton rojo");
    }//GEN-LAST:event_jBRojoActionPerformed

    private void jBAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAzulActionPerformed
        // TODO add your handling code here:
        jBRojo.setVisible(false);
        jBVerde.setVisible(false);
        jBInicio.setVisible(false);
        jLabelMensaje.setText("Has pulsado el boton azul");
    }//GEN-LAST:event_jBAzulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAzul;
    private javax.swing.JButton jBInicio;
    private javax.swing.JButton jBReset;
    private javax.swing.JButton jBRojo;
    private javax.swing.JButton jBVerde;
    private javax.swing.JLabel jLabelMensaje;
    // End of variables declaration//GEN-END:variables
}
